name: Infrastructure Build Pipeline

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm deployment'
        required: true
        default: 'no'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # ✅ Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      # ✅ Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.LOCATION }}

      # ✅ Step 4: Verify AWS credentials
      - name: Verify AWS credentials
        run: aws sts get-caller-identity

      # ✅ Step 5: Format Terraform files
      - name: Terraform FMT
        working-directory: ./terraform
        run: terraform fmt -recursive

      # ✅ Step 6: Initialise Terraform
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # ✅ Step 7: Validate Terraform
      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      # ✅ Step 8: Terraform Plan
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan

      # ✅ Step 9: Terraform Apply
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
